name: Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true

jobs:
  test_and_release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up Python environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install poetry twine wheel
        poetry install --no-root

    - name: Add JCloud auth token
      run: |
        mkdir -p ~/.jina
        touch ~/.jina/config.json
        echo "{\"auth_token\": \"${WOLF_TOKEN}\"}" > ~/.jina/config.json
        echo "{\"auth_token\": \"${WOLF_TOKEN}\"}" > ~/.jina/wolf.json
        echo ~/.jina/config.json
      env:
        WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}

    - name: Run tests
      run: |
        source .venv/bin/activate
        export PYTHONPATH=$(pwd)
        poetry run python -m unittest discover tests/
      env:
        RETRIEVAL_OPENAI_KEY: ${{ secrets.RETRIEVAL_OPENAI_KEY }}

    - name: Build and upload package
      if: ${{ success() }}
      run: |
        source .venv/bin/activate
        poetry build
        echo ${{ secrets.TWINE_PASSWORD }} | twine upload --repository-url https://upload.pypi.org/legacy/ -u ${{ secrets.TWINE_USERNAME }} -p ${{ secrets.TWINE_PASSWORD }} dist/*
      env:
        RELEASE_TAG: ${{ github.event.inputs.release_tag }}
