name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Python 3.10
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.10

    - name: Set up Python environment
      run: |
        python3.10 -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root

    - name: Run tests
      run: |
        source .venv/bin/activate
        poetry run pytest tests/
