name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Clear Python cache
      run: |
        sudo rm -rf /opt/hostedtoolcache/*/*/*/bin/python*

    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root

    - name: Run tests
      run: |
        poetry run pytest tests/
